AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Real-time e-commerce order processing pipeline using DynamoDB Streams,
  EventBridge Pipes, and Lambda with comprehensive error handling.

Resources:
  # 1. DynamoDB Table for Orders
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # 2. SQS Dead-Letter Queue for Error Handling
  PipeDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: order-processing-dlq
      MessageRetentionPeriod: 1209600  # 14 days

  # 3. IAM Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # 4. Lambda Function for Standard Order Processing
  StandardOrderProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StandardOrderProcessorLambda
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              """
              Processes standard orders from EventBridge Pipes.
              Filters for orders > $100, status = pending/shipped, excludes test emails.
              """
              batch_item_failures = []
              
              # EventBridge Pipes sends records as a list directly
              records = event if isinstance(event, list) else event.get('Records', [])
              
              print(f"Received {len(records)} records for standard processing.")
              
              for record in records:
                  try:
                      # Extract order details from DynamoDB Stream record
                      order_id = record['dynamodb']['Keys']['orderId']['S']
                      new_image = record['dynamodb'].get('NewImage', {})
                      event_name = record.get('eventName', 'UNKNOWN')
                      
                      # Extract order attributes
                      order_status = new_image.get('orderStatus', {}).get('S', '')
                      amount_str = new_image.get('amount', {}).get('N', '0')
                      customer_email = new_image.get('customerEmail', {}).get('S', '')
                      customer_name = new_image.get('customerName', {}).get('S', 'Unknown')
                      amount = float(amount_str)
                      
                      # Apply business logic filtering
                      # Filter 1: Order status must be pending or shipped
                      # Filter 2: Order amount must be greater than $100
                      # Filter 3: Exclude test emails (ending with @test.com)
                      
                      if order_status in ['pending', 'shipped'] and amount > 100 and not customer_email.endswith('@test.com'):
                          print(f"✓ Processing standard order: {order_id}")
                          print(f"  - Event: {event_name}")
                          print(f"  - Customer: {customer_name} ({customer_email})")
                          print(f"  - Status: {order_status}")
                          print(f"  - Amount: ${amount:.2f}")
                          
                          # ===== ADD YOUR BUSINESS LOGIC HERE =====
                          # Examples:
                          # - Send order confirmation email
                          # - Update inventory system
                          # - Trigger fulfillment workflow
                          # - Send notification to warehouse
                          # - Update analytics database
                          # ========================================
                          
                      else:
                          # Log why the order was skipped
                          skip_reasons = []
                          if order_status not in ['pending', 'shipped']:
                              skip_reasons.append(f"status={order_status}")
                          if amount <= 100:
                              skip_reasons.append(f"amount=${amount:.2f}")
                          if customer_email.endswith('@test.com'):
                              skip_reasons.append("test email")
                          
                          print(f"✗ Skipping order {order_id}: {', '.join(skip_reasons)}")
                          
                  except Exception as e:
                      # Log the error and add to batch failures for retry
                      print(f"ERROR processing record: {str(e)}")
                      print(f"Record data: {json.dumps(record, default=str)}")
                      batch_item_failures.append({
                          'itemIdentifier': record['dynamodb']['SequenceNumber']
                      })
              
              # Return failed items for automatic retry
              return {'batchItemFailures': batch_item_failures}
      Timeout: 60
      MemorySize: 256

  # 5. Lambda Function for Premium Order Processing
  PremiumOrderProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: PremiumOrderProcessorLambda
      Runtime: python3.9
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json

          def lambda_handler(event, context):
              """
              Processes premium high-value orders from EventBridge Pipes.
              Filters for orders > $1000 with status transition: pending → shipped.
              """
              batch_item_failures = []
              
              # EventBridge Pipes sends records as a list directly
              records = event if isinstance(event, list) else event.get('Records', [])
              
              print(f"Received {len(records)} records for premium processing.")
              
              for record in records:
                  try:
                      # Extract order details
                      order_id = record['dynamodb']['Keys']['orderId']['S']
                      old_image = record['dynamodb'].get('OldImage', {})
                      new_image = record['dynamodb'].get('NewImage', {})
                      event_name = record.get('eventName', 'UNKNOWN')
                      
                      # Extract status information for transition detection
                      old_status = old_image.get('orderStatus', {}).get('S', '')
                      new_status = new_image.get('orderStatus', {}).get('S', '')
                      
                      # Extract order value
                      amount_str = new_image.get('amount', {}).get('N', '0')
                      amount = float(amount_str)
                      
                      # Extract customer information
                      customer_email = new_image.get('customerEmail', {}).get('S', '')
                      customer_name = new_image.get('customerName', {}).get('S', 'Unknown')
                      
                      # Premium order criteria:
                      # 1. Order amount > $1000
                      # 2. Status transition from "pending" to "shipped"
                      # 3. Must be a MODIFY event (status change)
                      
                      if old_status == 'pending' and new_status == 'shipped' and amount > 1000:
                          print(f"★ Processing PREMIUM high-value order: {order_id}")
                          print(f"  - Customer: {customer_name} ({customer_email})")
                          print(f"  - Amount: ${amount:.2f}")
                          print(f"  - Status Transition: {old_status} → {new_status}")
                          print(f"  - Priority: HIGH VALUE CUSTOMER")
                          
                          # ===== ADD YOUR PREMIUM BUSINESS LOGIC HERE =====
                          # Examples:
                          # - Assign personal customer service representative
                          # - Send premium shipping notification
                          # - Trigger white-glove delivery service
                          # - Send personalized thank you gift
                          # - Alert VIP customer support team
                          # - Update CRM with high-value customer flag
                          # - Trigger loyalty points bonus
                          # ===============================================
                          
                      else:
                          # Log why this wasn't processed as premium
                          skip_reasons = []
                          if old_status != 'pending':
                              skip_reasons.append(f"old_status={old_status}")
                          if new_status != 'shipped':
                              skip_reasons.append(f"new_status={new_status}")
                          if amount <= 1000:
                              skip_reasons.append(f"amount=${amount:.2f}")
                          
                          print(f"✗ Skipping order {order_id}: {', '.join(skip_reasons)}")
                          
                  except Exception as e:
                      # Log the error and add to batch failures
                      print(f"ERROR processing premium record: {str(e)}")
                      print(f"Record data: {json.dumps(record, default=str)}")
                      batch_item_failures.append({
                          'itemIdentifier': record['dynamodb']['SequenceNumber']
                      })
              
              # Return failed items for automatic retry
              return {'batchItemFailures': batch_item_failures}
      Timeout: 60
      MemorySize: 256

  # 6. IAM Role for EventBridge Pipes
  PipeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: pipes.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBStreamSourcePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt OrdersTable.StreamArn
        - PolicyName: LambdaTargetPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource:
                  - !GetAtt StandardOrderProcessorLambda.Arn
                  - !GetAtt PremiumOrderProcessorLambda.Arn
        - PolicyName: SqsDLQTargetPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt PipeDLQ.Arn

  # 7. EventBridge Pipe for Standard Orders
  StandardOrderPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: StandardOrderPipe
      Description: Processes standard orders from DynamoDB Streams (INSERT and MODIFY events)
      RoleArn: !GetAtt PipeRole.Arn
      Source: !GetAtt OrdersTable.StreamArn
      SourceParameters:
        FilterCriteria:
          Filters:
            - Pattern: '{"eventName":["INSERT","MODIFY"]}'
        DynamoDBStreamParameters:
          StartingPosition: LATEST
          BatchSize: 10
          DeadLetterConfig:
            Arn: !GetAtt PipeDLQ.Arn
          MaximumRetryAttempts: 3
          OnPartialBatchItemFailure: AUTOMATIC_BISECT
      Target: !GetAtt StandardOrderProcessorLambda.Arn
      TargetParameters:
        LambdaFunctionParameters:
          InvocationType: REQUEST_RESPONSE

  # 8. EventBridge Pipe for Premium High-Value Orders
  PremiumOrderPipe:
    Type: AWS::Pipes::Pipe
    Properties:
      Name: PremiumOrderPipe
      Description: Processes premium high-value orders (status transitions from pending to shipped)
      RoleArn: !GetAtt PipeRole.Arn
      Source: !GetAtt OrdersTable.StreamArn
      SourceParameters:
        FilterCriteria:
          Filters:
            - Pattern: '{"eventName":["MODIFY"]}'
        DynamoDBStreamParameters:
          StartingPosition: LATEST
          BatchSize: 5
          DeadLetterConfig:
            Arn: !GetAtt PipeDLQ.Arn
          MaximumRetryAttempts: 3
      Target: !GetAtt PremiumOrderProcessorLambda.Arn

Outputs:
  OrdersTableName:
    Description: Name of the DynamoDB Orders table
    Value: !Ref OrdersTable
    Export:
      Name: !Sub '${AWS::StackName}-OrdersTableName'
  
  OrdersTableStreamArn:
    Description: ARN of the DynamoDB Orders table stream
    Value: !GetAtt OrdersTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-OrdersTableStreamArn'
  
  PipeDLQUrl:
    Description: URL of the Dead-Letter SQS Queue
    Value: !Ref PipeDLQ
    Export:
      Name: !Sub '${AWS::StackName}-DLQUrl'
  
  PipeDLQArn:
    Description: ARN of the Dead-Letter SQS Queue
    Value: !GetAtt PipeDLQ.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DLQArn'
  
  StandardOrderProcessorLambdaArn:
    Description: ARN of Standard Order Processor Lambda
    Value: !GetAtt StandardOrderProcessorLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-StandardLambdaArn'
  
  PremiumOrderProcessorLambdaArn:
    Description: ARN of Premium Order Processor Lambda
    Value: !GetAtt PremiumOrderProcessorLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PremiumLambdaArn'
  
  StandardOrderPipeArn:
    Description: ARN of the Standard Order EventBridge Pipe
    Value: !GetAtt StandardOrderPipe.Arn
    Export:
      Name: !Sub '${AWS::StackName}-StandardPipeArn'
  
  PremiumOrderPipeArn:
    Description: ARN of the Premium Order EventBridge Pipe
    Value: !GetAtt PremiumOrderPipe.Arn
    Export:
      Name: !Sub '${AWS::StackName}-PremiumPipeArn'
