  # This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build 10-10-2025(ORDER)

on:
  push:
    paths:
      - '10-10-2025/Inter-Microservice-Communication/Emp-Order-Service/**'
  pull_request:
    paths:
      - '10-10-2025/Inter-Microservice-Communication/Emp-Order-Service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: tiger
          MYSQL_DATABASE: swag
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('10-10-2025/Inter-Microservice-Communication/Emp-Employee-Service/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    - name: Build and Test with Maven
      working-directory: 10-10-2025/Inter-Microservice-Communication/Emp-Employee-Service/
      run: mvn clean verify
